[pytest]
testpaths = tests
filterwarnings =
    ignore:Using `httpx` with `starlette.testclient` is deprecated.*:starlette.exceptions.StarletteDeprecationWarning
    ignore:builtin type swigvarlink has no __module__ attribute:DeprecationWarning
    ignore:'audioop' is deprecated and slated for removal in Python 3\.13:DeprecationWarning
