@echo off
REM Program: switch Pat-FunASR default model hub between ModelScope and HuggingFace.
chcp 65001 >nul
setlocal EnableExtensions
cd /d "%~dp0"

set "TARGET=%~1"
if defined TARGET call :normalize_target "%TARGET%"

if "%TARGET%"=="status" goto :status
if "%TARGET%"=="ms" goto :write
if "%TARGET%"=="hf" goto :write

echo.
echo 请选择默认模型来源：
echo   1. ModelScope (ms)
echo   2. HuggingFace (hf)
echo   3. 查看当前设置
echo.
set /p "CHOICE=输入 1/2/3 后回车: "
if "%CHOICE%"=="1" set "TARGET=ms"
if "%CHOICE%"=="2" set "TARGET=hf"
if "%CHOICE%"=="3" goto :status
if not defined TARGET (
  echo 未选择有效来源。
  exit /b 1
)

:write
> ".env.local.bat" echo @echo off
>> ".env.local.bat" echo REM Program: local Pat-FunASR runtime environment generated by switch_model_hub.bat.
>> ".env.local.bat" echo set "FUNASR_MODEL_HUB=%TARGET%"
echo 已切换默认模型来源为 "%TARGET%"。
echo 配置文件："%CD%\.env.local.bat"
echo 重启 API / WebUI 后生效。
exit /b 0

:normalize_target
set "TARGET=%~1"
if "%TARGET%"=="modelscope" set "TARGET=ms"
if "%TARGET%"=="ModelScope" set "TARGET=ms"
if "%TARGET%"=="huggingface" set "TARGET=hf"
if "%TARGET%"=="HuggingFace" set "TARGET=hf"
exit /b 0

:status
if exist ".env.local.bat" (
  call ".env.local.bat"
)
if not defined FUNASR_MODEL_HUB (
  echo 当前默认模型来源：未设置（使用代码内默认配置）
) else (
  echo 当前默认模型来源："%FUNASR_MODEL_HUB%"
)
exit /b 0
